#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BabbyJotz.Android.Resource", IsApplication=true)]

namespace BabbyJotz.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int content_new_event = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_stat_notify = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int toolbar_new_entry = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public const int BabbyActionBar = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int BabbyTextView = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int BabbyTheme = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Theme_Splash = 2130968579;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BabbyTheme;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
